matrix:
  include:
  - language: smalltalk
    os:
    - linux
    smalltalk:
    - Pharo64-8.0
  - language: c
    addons:
      apt:
        packages:
        - make
        - git
        - libgtk-3-0
    install:
    - make dist
    script:
    - echo " "
deploy:
  provider: releases
  on: language=C
  api_key:
    secure: eCpVcEjKPQ7YmySVEsJYrjwt5cLOkny21/JQ1QFoF2vrgVoqm8NniqCaB3pvSxiRIsM5fSAm01V4bQ0jtHVRGzXA+0n9nCTKyB1pLAtKn4xACwsP9qrltIUrvDPm+hFJfeMDogoR5oo3Lh3vPxzkxdlFtXQL5IA0b8G2/yjwtughcYOgYnxp8YYUBDsvY6qBEpLqUdYmLPSdTJ8iV1c6N72EePQo37uoHhlQ6oIiiIjcCG5gZcPwURyDWbLKfyMfNemH8c+6l7CDxtKyXtOz/5d/gevu2V+lM4bLse5J0P1c/xFfdCPbdIahEf7JItIG0iHdZOR7hlZ0nezekvigs34lUW9L+MyilIxeobxS3LuPru3AOqob+FicZHhCFfxDcS/EhDa0yzJDnJ5qVwGAALzW6UriKaTruxC4+BkmdgXH/lO3Sd4AJMd9BEH9q4VHmN9E8gj9XNNM9C2S1DHlBoNWWNgyNUGQvR55SgLEoOfPHBOBu0Itc2SJyCv0TqkkVJMiiKEoU3fFWe2+Qp6L8nW/+OH57bKAmCwURGC7r+gFceDu/xgYk9a79P/J2wCcK2b/uxLTpK05rTy1NQPP6qKH+x4OPHj6UIcw5UobchEM55wDt3dhYvlDN/Adw321AWNGdD1BEvRl0Yf8OVFJkencF/T/VADvunlSDARIIr0=
  skip_cleanup: true
  file: "./release.zip"
  on:
    repo: noha/Zuul


