matrix:
  include:
  - language: smalltalk
    os:
    - linux
    smalltalk:
    - Pharo64-8.0
  - language: c
    addons:
      apt:
        packages:
        - make
        - git
        - libgtk-3-0
    install:
    - make dist
    script:
    - echo " "
deploy:
  provider: releases
  on: language=C
  api_key:
    secure: J5Sv2kF8KF2bchtwek51uCR1IY3qWM3SIR4bEq3OZYd1qaGq+Mw7/xi5hBNlXIYTP80Sd1wAzEjGxZK/ZeFZ2cNuP//paiM28lD4sRW9EY77kNgBXpo6LbJWWqH1nVD3/hnTEwoUW7mYnPe1xjXkilgApagAjzvRWvBKbP7UinftB5fUvUyR3MPBcdrAam9AiXPCL9tWGaPf9B0tj5HoEM2PETVR90jyD7oq4X1miLVSIcq2150QLBte3ud8VNoQBfT6Xx0q+WTJKGy4I75bslgVggrt2pVboapoOt8BvhaZicr8ZX1yX49FfB/idjSwGNZ8a2kDMBA0nsA+4ihEp1Le33ujGrzpqv+g25/qeKicpi6W6Dqz5NpigJKof8ourxG7xynu2c3SJGnh6Ek/x4TDvya1l+eD9vgfT/aTCY7Hhu5cdQILIPZslUZ42b5nq90yXnBxxDdHq22kPYj0HHNOUtRSIQX33BO8VYLdFJyEWPB+xcCJ2Kv1hiwNNQpUsp97deOJfGGXwiIsJEOiXJlybCKY0oKpxw1TbHQA7qrGcK2oYegfxTMWJDcU592KBqIyC8YX2yC7YTb26WHBPJgzfOYPNMDABM47bvkUP691ZLB1v7e8lHd4lur4cMMiaYD2+7jU/rKJ2YGE1JjZDtgD4x2EdpE/BS4bFqTvVA4=
  file_glob: true
  file: "./release.zip"
  skip_cleanup: true
  on:
    repo: noha/Zuul
