matrix:
  include:
  - language: smalltalk
    os:
    - linux
    smalltalk:
    - Pharo64-8.0
  - language: c
    addons:
      apt:
        packages:
        - make
        - git
        - libgtk-3-0
    install:
    - make dist
    script:
    - echo " "
deploy:
  provider: releases
  api_key:
    secure: Ee9pZ7Dt5dUG+mnNhaPqdjodFztG3Ei3uqu08+xWWldvgFeDC9xdvoag24cWyXhjCxYsJzKkCkaR5rzgck1bnJ6Nfj/v0b1jUuj2zVbTgZTIsw6aNMhjCM2ACLGS515AeGObImtdu45NXetkLLqmD+Hm78aFCmt2id7m6mnXbIlJtwLv+yvKO6LCALefGlPqGdvy8Sy78QhcH4kkz3JUBIOMGvVidv7Z/t/o/jqzYGXzVgenW8gJBm3NenVQDGbVOaFIUDhrbEI7y9N3IXJB2f8O5hetEMz2KQV9lXNWeTqq6byNN3OpQmMTBZ9UwY3kyefjUfKj3ib8NXf4NccYqbK3ROcMwDUQKxOE1znaUrdxX1WqfPLAccmt15/akUmtgylbMkvlfhz6poqTHVqXxJXYT0xKJEPkKEwx0BS9zm0XmzsmjsGF37U/aRuqeTaqAuX7OpkYZJZcEML0o78icNqXOIrTl7BUCmQI44zWFSwbGLXoyiIltUfpprwh8cnoUzw9FylHWHv3msJ/RFhj00q+sIDLF0Uznjpcw5PFj/J0STWh0SZHbaXIlk68KyWfEOgNs5706AOftBRGHktta8e6LVdA87utNb9T6cf9PDLlGmL44Ugh0bI26kMyqxXElECmdbBg8G1JX++4Va45oKiiDJDkPUvQg/pK8z9UccY=
  skip_cleanup: true
  file: "./release.zip"
  on:
    repo: noha/Zuul
    language: C
    tags: true
